language: node_js

node_js:
- '10.6.0'
- '5'
- '6'
- '7'
- '8'
- '9'

sudo: false

# Allow greenkeeper to commit package-lock.json, greenkeeper-lockfile-upload
# will run only on the first listed node_js version:
before_install: npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

env:
  global:
    secure: GJS1HncilhBL5EOtWYCTeblDN2P0VHNTRoqrBAJeaMNA4m3an12HfcLqXTDk+PoOViPwYoiEWTo2TP9i7ryTUoW59U1WqmzqLujxcWDol8uewGg1SGFv/fiHMhMsgouWhbqUp9u3AOjevLpn7fCTACKxb1BsPhbDR3eeJfnxb1g=
