language: node_js

node_js:
- '10.6.0'
- '5'
- '6'
- '7'
- '8'
- '9'

sudo: false

env:
  global:
    secure: GJS1HncilhBL5EOtWYCTeblDN2P0VHNTRoqrBAJeaMNA4m3an12HfcLqXTDk+PoOViPwYoiEWTo2TP9i7ryTUoW59U1WqmzqLujxcWDol8uewGg1SGFv/fiHMhMsgouWhbqUp9u3AOjevLpn7fCTACKxb1BsPhbDR3eeJfnxb1g=
